### ISSUE TITLE
Example of custom pickler for noncase class in readme

### ISSUE THREAD

**Issue by antonkulaga** [sjrd/scala-js-pickling#1]
It would be nice to see an example of pickler for some complex non-case class as from readme it is not clear how to write custom picklers

**Comment by mathieuleclaire** [comment]
I am also very interrested in seeing some examples with none case classes :) !

**Comment by sjrd** [comment]
Closing as I'm about to [archive](https://help.github.com/articles/about-archiving-repositories/) this repository.
