### ISSUE TITLE
Any chance for Play 2.4 support?

### ISSUE THREAD

**Issue by xsistens** [sjrd/scala-js-pickling#17]
Hey guys,
first i want to appreciate your work with scala.js and the pickling.
I try to setup a project with scala.js and play 2.4 and want to use scala-js-pickling too.
But after the changes in the play-json framework in 2.4 its not working anymore.
Now i wanted to ask if there is any chance for an update for the play-json support to the new version?

thx in advance!

**Comment by sjrd** [comment]
Closing as I'm about to [archive](https://help.github.com/articles/about-archiving-repositories/) this repository.
