### ISSUE TITLE
0.4 ?

### ISSUE THREAD

**Issue by mathieuleclaire** [sjrd/scala-js-pickling#4]
Hi, 
I would be very pleased to try the third part of the scala-js trilogy: scala-js-pickling with the 0.5 scala-js. When do you plan to deploy the 0.4 version (relying on scaja-js 0.5) ?

Thanks !

**Comment by sjrd** [comment]
Version 0.3.1 is published for Scala.js 0.5.

**Comment by mathieuleclaire** [comment]
Ok, thanks. I didn't read that information on the first page. I will test it now !
