### ISSUE TITLE
Doesn't work out of the box with Scala.js 0.5.3

### ISSUE THREAD

**Issue by phlegmaticprogrammer** [sjrd/scala-js-pickling#6]
But of course one can just check out the repository and adjust the version by hand.

**Comment by sjrd** [comment]
Have you tried with 0.5.4? There was [a bug in 0.5.3](https://github.com/scala-js/scala-js/issues/897) that prevent it from reading some classes compiled with 0.5.0 and 0.5.1. The bug has been fixed in 0.5.4.

**Comment by phlegmaticprogrammer** [comment]
Ah ok, good to know. I still have everything on 0.5.3, but will switch then soon. 

Apart from that, I just had to modify the plugin version to be 0.5.3, and then it worked. The issue I submitted was just about that just including the library dependency as described in the readme was not enough, because no such build was found in the public repository, so you have to build it yourself.
