### ISSUE TITLE
Implicit materialisation of fields exported by @JSExport

### ISSUE THREAD

**Issue by jlc** [sjrd/scala-js-pickling#9]
Hi,

We have a project relying on a common model composed of case classes.
It is used used by both the backend as well as the frontend (based on scalajs).

The serialisation of those classes is done with scala-js-pickling. Moreover, as we need to access their members from js, we need to export them with @JSExport, so we've just added the corresponding annotations:

``` scala
@JSExport
case class User(
  @(JSExport @field) id: Int,
  @(JSExport @field) email: String,
  @(JSExport @field) realName: String
)
```

Unfortunately, when registering it with:

```
PicklerRegistry.register[User]
```

It now failed with:

```
could not find implicit value for parameter unpickler: org.scalajs.spickling.Unpickler[...User]
```

Digging within the PicklerMaterializers macros and simply printing the list of accessors which are used to generate the implicit GenPickler, we can see the accessors generated by the scala-js compiler:

```
tpe: ....User
accessors: List(value email, value realName, value $js$exported$prop$email, value $js$exported$prop$realName)
```

The solution might be to filter out the symbols exported by scala-js.
Here is a dummy approach (at least it works):

``` scala
object PicklerMaterializersImpl {
  def materializePickler[T: c.WeakTypeTag](c: Context): c.Expr[Pickler[T]] = { 
    ...
    val accessors = (tpe.declarations collect {
      case acc: MethodSymbol if acc.isCaseAccessor => acc 
    }).toList.filter(!_.fullName.contains("$js$exported"))  
    ...
  }

  def materializeUnpickler[T: c.WeakTypeTag](c: Context): c.Expr[Unpickler[T]] = {
    ...
    val accessors = // same trick as in materializePickler()
    ...
  }
}
```

As you know perfectly how scala-js handle the @JSExport, no doubt you will come out with a better solution.

Wish you a nice day!

Jean Luc

**Comment by sjrd** [comment]
Closing as I'm about to [archive](https://help.github.com/articles/about-archiving-repositories/) this repository.
